sap.ui.define([
    "sap/m/MessageToast"
], function(MessageToast) {
    'use strict';

    return {
        downloadInvoice: function(oBindingContext, aSelectedContexts) {
            var aContexts = aSelectedContexts || [oBindingContext];
            if (!aContexts || aContexts.length === 0 || !aContexts[0]) {
                MessageToast.show("Please select an invoice.");
                return;
            }

            if (!window.jspdf || !window.jspdf.jsPDF) {
                MessageToast.show("PDF library not loaded.");
                return;
            }

            var oContext = aContexts[0];
            var oData = oContext.getObject();

            var doc = new window.jspdf.jsPDF();
            // Header
            doc.setFontSize(22);
            doc.setTextColor(40, 40, 40);
            doc.text("Supplier Invoice", 14, 22);

            // Document Info Header Box
            doc.setFontSize(10);
            doc.setTextColor(100, 100, 100);
            doc.text("Generated by SAP Fiori Invoice App", 14, 30);

            // Section 1: General Details
            doc.setFontSize(14);
            doc.setTextColor(0, 0, 0);
            doc.text("General Details", 14, 45);
            doc.setLineWidth(0.5);
            doc.setDrawColor(200, 200, 200);
            doc.line(14, 48, 196, 48);

            doc.setFontSize(10);
            doc.setTextColor(0, 0, 0);

            // Left Column
            doc.setFont(undefined, 'bold');
            doc.text("Invoice Number:", 14, 58);
            doc.setFont(undefined, 'normal');
            doc.text((oData.SupplierInvoiceNumber || oData.invoiceID || oData.ID || "").toString(), 55, 58);

            doc.setFont(undefined, 'bold');
            doc.text("Transaction Type:", 14, 66);
            doc.setFont(undefined, 'normal');
            doc.text((oData.TransactionType || "INVOICE").toString(), 55, 66);

            doc.setFont(undefined, 'bold');
            doc.text("Goods Receipt:", 14, 74);
            doc.setFont(undefined, 'normal');
            doc.text((oData.refGoodsReceiptID || "N/A").toString(), 55, 74);

            // Right Column
            doc.setFont(undefined, 'bold');
            doc.text("Invoice Date:", 110, 58);
            doc.setFont(undefined, 'normal');
            doc.text((oData.InvoiceDate || "N/A").toString(), 145, 58);

            doc.setFont(undefined, 'bold');
            doc.text("Posting Date:", 110, 66);
            doc.setFont(undefined, 'normal');
            doc.text((oData.PostingDate || "N/A").toString(), 145, 66);

            doc.setFont(undefined, 'bold');
            doc.text("Fiscal Year:", 110, 74);
            doc.setFont(undefined, 'normal');
            doc.text((oData.FiscalYear || "N/A").toString(), 145, 74);

            // Section 2: Financial Information
            doc.setFontSize(14);
            doc.setFont(undefined, 'normal');
            doc.text("Financial Information", 14, 95);
            doc.line(14, 98, 196, 98);

            doc.setFontSize(10);
            
            // Financial Details
            doc.setFont(undefined, 'bold');
            doc.text("Gross Amount:", 14, 108);
            doc.setFont(undefined, 'normal');
            doc.text((oData.GrossAmount || "0.00").toString(), 55, 108);

            doc.setFont(undefined, 'bold');
            doc.text("Currency:", 14, 116);
            doc.setFont(undefined, 'normal');
            doc.text((oData.Currency || "EUR").toString(), 55, 116);

            doc.setFont(undefined, 'bold');
            doc.text("Tax Code:", 110, 108);
            doc.setFont(undefined, 'normal');
            doc.text((oData.TaxCode || "N/A").toString(), 145, 108);


            var sFileName = "Invoice_" + (oData.SupplierInvoiceNumber || oData.invoiceID || "Export") + ".pdf";
            doc.save(sFileName);
            MessageToast.show("Invoice downloaded successfully.");
        }
    };
});
